### ISSUE TITLE
Travailles

### ISSUE THREAD

**Issue by AmauryFaveriel** [ThomasDorothee/Portfolio#2]
On sait que tu fous rien, fais pas semblant.

**Comment by Doriangue** [comment]
slt cv amomo

**Comment by Doriangue** [comment]
j'avoue tu fous rien

**Comment by Doriangue** [comment]
💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩

**Comment by AmauryFaveriel** [comment]
On est tous d'accord, en plus c'est Rémi qui a écrit l'issue au départ

**Comment by Doriangue** [comment]
C'est une ichoue
